server:
  port: ${PORT:5000}
  error:
    whitelabel:
      enabled: false
    path: /error

spring:
  datasource:
    url:  ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

tv:
  view:
    number-per-page: 15